#!/usr/bin/env tcsh
setenv RUN 1
cp kug$RUN.dat fort.15
if ( -e star$RUN.inf) ln star$RUN.inf fort.3
if ( -e star$RUN.cwr) ln star$RUN.cwr fort.2
if ( -e star$RUN.bin) ln star$RUN.bin fort.1
if ( -e star$RUN.rand) ln star$RUN.rand fort.91
if ( -e fort.61 ) mv fort.61 star$RUN.bindat.$$.old
echo "Run module used: " `date` ../$1 >> star$RUN.list.$$
../$1 >> star$RUN.list.$$ || if ( -e fort.4 ) mv fort.4 star$RUN.last ; if ( -e fort.11 ) mv fort.11 star$RUN.lastbin ; if ( -e fort.61 ) mv fort.61 star$RUN.bindat.$$ ; if ( -e fort.85 ) mv fort.85 fort.85.$$ ; if ( -e fort.86 ) mv fort.86 fort.86.$$ ; if ( -e fort.87 ) mv fort.87 fort.87.$$ ; if ( -e fort.88 ) mv fort.88 fort.88.$$ ; exit
if ( -e fort.4 ) mv fort.4 star$RUN.last
if ( -e fort.11 ) mv fort.11 star$RUN.lastbin
if ( -e fort.61 ) mv fort.61 star$RUN.bindat.$$
if ( -e fort.85 ) mv fort.85 fort.85.$$
if ( -e fort.86 ) mv fort.86 fort.86.$$
if ( -e fort.87 ) mv fort.87 fort.87.$$
if ( -e fort.88 ) mv fort.88 fort.88.$$
exit

