C+
C  ***   ENTRY DCODE   ***
C
C  READS ASCII DATA FROM FILE AND DECODES IT INTO BINARY DATA, THUS
C  DECODING THE NCODE PROCESS
C
C  USAGE: CALL DCODE( LUN , DAT , NDAT , IERR)
C
C  WHERE    LUN      IS THE UNIT FOR THE ASCII INPUT              (INPUT
C           DAT      IS AN ARRAY CONTAINING THE BINARY DATA        OUTPU
C           NDAT     IS THE NUMBER OF VALID DATA POINTS            OUTPU
C           IERR     ERROR CODE (=0 IF NO ERRORS, < 0 IF ERRORS    OUTPU
C                    OCCUR
C-
      SUBROUTINE DCODE(KIN,V,NDATA,IERR,ILKIN)
      IMPLICIT REAL*4 (A-H,O-Z),INTEGER*4(I-N)
      CHARACTER*1 LINE
      CHARACTER*80 ZL
      DIMENSION V(*),LINE(76)
C
      IERR=0
C
      ILKIN=ILKIN+1
      IERR=-10
      READ(KIN,102,ERR=999,END=998)
     &   NDATA,NLINE,NWRD,NCHR,NASCII,NLAST,DATMIN,SCALE
      IERR=0
*     WRITE(6,102)NDATA,NLINE,NWRD,NCHR,NASCII,NLAST,DATMIN,SCALE
 102  FORMAT(2X,I10,I8,4I3,1P,2E20.13,8X)
      IF(NLINE.EQ.0) THEN
      DO 11 I=1,NDATA
 11     V(I)=DATMIN 
      GOTO 10
      END IF
*
      SCALE=1./SCALE
        IDATA=0
      DO 9 ILINE=1,NLINE
      ILKIN=ILKIN+1
       IERR=-20
       READ(KIN,101,ERR=999,END=998)(LINE(K),K=1,76)
       IERR=0
 101  FORMAT(2X,76A1)
      ipoint=ipoint+1
        ICHR=1
        DO 5 IWRD=1,NWRD
          IDATA=IDATA+1
          IF(IDATA.GT.NDATA) GOTO 10
          IV=0
          ICHR=ICHR+NCHR
          DO 4 I=1,NCHR
            JCHR=ICHR-I
            KV=ICHAR(LINE(JCHR))-32
            IF(KV.EQ.63)KV=26
 4          IV=IV*NASCII+KV
          VDAT=IV
          V(IDATA)=VDAT*SCALE+DATMIN
 5      CONTINUE
 9    CONTINUE
 10   CONTINUE
      RETURN
      WRITE(6,102)NDATA,NLINE,NWRD,NCHR,NASCII,NLAST,DATMIN,SCALE
 998  CONTINUE
      PRINT*,' Reached End of File in DCODE '
      RETURN
 999  CONTINUE
      PRINT*,' Error Exit in DCODE '
      RETURN
      END
