      SUBROUTINE PSTART(IJK,ISET,ILAUF,ICWR)
      IMPLICIT REAL*8(A-H,O-Z),INTEGER(I-K,M-N),LOGICAL(L)
      INCLUDE 'compar.f'
      INCLUDE 'equiv.f'
      INCLUDE 'plotsplo.f'
C
      INCLUDE 'frm2.f'
C**INCLUDE FORMATS FOR READ AND WRITE ON UNIT 10*********
      PRINT*,' This is PSTART with IJK=',IJK,
     * ' ILAUF=',ILAUF,' IMODA=',IMODA
      IF(IJK.EQ.3)GOTO 333
      IF(ILAUF.GT.IMODA)GOTO 111
 333  CONTINUE
      CALL DECODE(IJK,ISET,ILAUF)
C
      MODA=IEI(1)
      NMOD=IEI(2)
      NJ=IEI(13)
      TIME=AEI(2)
      IF(MODA.LT.MOCNT(ILAUF))GOTO 333
      IF(MODA.EQ.MOCNT(ILAUF))PRINT*,' Model ',MODA,' found'
      IF(MODA.GT.MOCNT(ILAUF))THEN
      PRINT*,' MODA=',MODA,' Error in Model Read Order - STOP'
      STOP
      END IF
      WRITE(6,1001)MODA,NMOD,AEI(2)/YEAR
 1001 FORMAT(' MODEL MODA=',I3,' NMOD=',I5,' READ, T=',1PE9.2)
C
 111  CONTINUE
      IF(IJK.EQ.3)RETURN
      IF(IJK.EQ.1)RETURN
C
      NMAX=NPLOT
      IF(ILAUF.GT.IMODA)NMAX=NTIME
      IF(ILAUF.LE.IMODA)THEN
      WRITE(ZTEXT2,112)IEI(1),IEI(2)
      WRITE(ZTEXT3,113)TIME/YEAR
 112  FORMAT(' (M0)MODA=',I3,' NMOD=',I4,'(M0)$',32X)
 113  FORMAT(' (M0)TIME=',1PE9.2,1X,' YRS.(M0)$',30X)
      ELSE
      WRITE(ZTEXT2,114)
      WRITE(ZTEXT3,114)
 114  FORMAT(' (M0)$',54X)
      END IF
      IF(ICWR.EQ.1.AND.ISET.EQ.1.AND.IMGO.NE.1)
     * WRITE(50+ILAUF,5003)MODA,TIME,NMOD,ZTEXT2,ZTEXT3
      DO 223 ICOUNT=1,NMAX
      CALL XPLOT(ILAUF,ICOUNT)
      JS=6*(ICOUNT-1)
      IT=4*(ICOUNT-1)
      IU=5*(ICOUNT-1)
      ZTEXT1=ZWORK(ICOUNT)
      IF(ILAUF.GT.IMODA)THEN
      JS=6*(NPLOT+ICOUNT-1)
      IT=4*(NPLOT+ICOUNT-1)
      IU=5*(NPLOT+ICOUNT-1)
      ZTEXT1=ZWORK(NPLOT+ICOUNT)
      END IF
      IW=IWORK(JS+1)
      XLEG=XWORK(IT+1)
          IF(XLEG.LE.0.D0)XLEG=5.D-1
      YLEG=XWORK(IT+2)
          IF(YLEG.LE.0.D0)YLEG=5.D-2
      LEG=LWORK(IT+1)
      XT5=XWORK(IT+3)
      YT5=XWORK(IT+4)
      LT5=LWORK(IT+2)
      LKUPA=LWORK(IT+3)
      LSCALE=LWORK(IT+4)
C
      DO 505 K=1,5
      IF(IWORK(JS+K+1).EQ.-2)GOTO 507
      MCOL(ICOUNT)=K
      IF(LSCALE)THEN
      ICNT=ICOUNT
      IF(ILAUF.GT.IMODA)ICNT=NPLOT+ICOUNT
      PAR(1,K)=PARY(2*K,ICNT)
      PAR(3,K)=PARY(2*K-1,ICNT)
      PAR(2,K)=(PAR(3,K)-PAR(1,K))/1.D1
      END IF
 505  CONTINUE
 507  CONTINUE
      IF(ICWR.EQ.1.AND.ISET.EQ.1.AND.IMGO.NE.1)
     * WRITE(50+ILAUF,5004)MCOL(ICOUNT),IW,(IMARK,N=1,4),XT5,YT5,
     * LT5,XLEG,YLEG,LEG,(LKUPA,N=1,4),
     * (ZNAM(I),(PAR(K,I),K=1,3),ZLINE(I),I=1,5),ZTEXT1
      NP=NJ-1
      IF(ILAUF.GT.IMODA)NP=NTP-1
      NMIN=2
      IF(ILAUF.GT.IMODA)NMIN=1
C
      IWRITE = 0
      DO 506 I=NMIN,NP
C
      IF(LSMO.AND.I.GT.NMIN)THEN
      LNEXT=.FALSE.
      DO 5060 K=1,MCOL(ICOUNT)
      LNEXT=LNEXT.OR.(DABS(VEC(K,I)-VEC(K,I-1)).LT.1.D-30)
 5060 CONTINUE
      IF(LNEXT)GOTO 506
      END IF
C
      IWRITE=IWRITE+1
      IF(IMGO.EQ.1)THEN
      WRITE(50,5005)(VEC(K,I),K=1,MCOL(ICOUNT))
      ELSE
      WRITE(50+ILAUF,5005)(VEC(K,I),K=1,MCOL(ICOUNT))
      END IF
 506  CONTINUE
C
      PRINT*,' From ',NP-NMIN+1,' possible records are ',IWRITE,
     * 'written '
C
      IF(IMGO.EQ.1.AND.ISET.EQ.1)THEN
C
      IOLIN=ILINES
      ILINES=ILINES+IWRITE
      DO 606 K=2,MCOL(ICOUNT)
      WRITE(11,*)'LINES ',IOLIN+1,ILINES
      WRITE(11,*)'XCOLUMN 1'
      WRITE(11,*)'YCOLUMN ',K
C
      IF(ILAUF.EQ.1.AND.K.EQ.2)THEN
      WRITE(11,*)'LIMITS ',XMINX,XMAXX,YMIN,YMAX
      WRITE(11,*)'BOX'
      WRITE(11,*)'EXPAND 1.0'
      WRITE(11,*)'XLABEL ',ZLINE(1)
      WRITE(11,*)'YLABEL ',ZLINE(2)
      END IF
C
      ILTYPE=ILTYPE+1
      IF(ILTYPE.GT.6)ILTYPE=0
C
      WRITE(11,*)'LTYPE ',ILTYPE
      WRITE(11,*)'CONNECT'
      WRITE(11,*)'EXPAND 0.7'
      WRITE(11,*)'RELOCATE 0. 0. '
      WRITE(11,*)'PUTLABEL  6'
C
 606  CONTINUE
      END IF
 223  CONTINUE
      RETURN
      END
